### PR TITLE
Add ‘kill’ and ‘ssh’ as globally available binaries

### PR DESCRIPTION
**Pull request by KittyGiraudel**
Hello! 👋  It seems we list a lot of unix commands as available binaries already so I thought `kill` and `ssh` would be fair game. Let me know if not.

### CODE REVIEW

**Comment by KittyGiraudel** [comment]
Would you accept a PR to add `aws` to this list? :)

**Comment by webpro** [comment]
Drifting off a tiny bit, but I'd accept a PR to add it!

Btw, you can do e.g. `ignoreBinaries: ["aws"]`

**Comment by KittyGiraudel** [comment]
@webpro That’s what we currently do, but I reckon `aws` is popular enough that it would make sense? I understand it’s debatable though.

**Comment by webpro** [comment]
Agreed, let's do it. There's things like `xcodebuild` and `gem` too. I'll think about boundaries better if/when it gets out of hand.

**Pull request merged**
