### PR TITLE
Stylelint plugin - fix issue where "customSyntax" property is not recognised as a resolved dependency

### LINKED ISSUE #799: 🐛 Stylelint: "customSyntax" config is not recognised as dependency usage
### Prerequisites

- [X] I'm using the latest version
- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://codesandbox.io/p/sandbox/zealous-northcutt-g94nf7

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Description of the issue

Including `"customSyntax": "postcss-less" ` in the stylelint config does not mark `postcss-less` as a used dependency. knip definitely detects the config file correctly, but there is nothing in the plugin code that checks this field. https://github.com/webpro-nl/knip/blob/main/packages/knip/src/plugins/stylelint/index.ts

Knip produces the following report:
```
Unused devDependencies (1)
postcss-less  package.json
```

## Workaround
By switching to a JS config, you can do
```
"customSyntax": require.resolve("postcss-less")
```
which causes the dependency to be correctly marked as used.

### PR DESCRIPTION
**Pull request by duncan-thacker**
Closes #799 
 
Adds `customSyntax` to the stylelint plugin. Includes a test case.

### CODE REVIEW

**Comment by duncan-thacker** [comment]
I can't run the tests locally as I'm on a windows machine. Pretty sure they'll pass though!

**Comment by webpro** [comment]
> I can't run the tests locally as I'm on a windows machine. Pretty sure they'll pass though!

Thanks for the PR. Should run fine on Windows? Use `bun run test` for Bun or `npm run test:node` for Node.js. Same as in CI. Can I ask if there's an issue with either of those?

**Comment by duncan-thacker** [comment]
```
C:\Work\knip> bun run test
$ bun test test/*.test.ts test/**/*.test.ts
The command line is too long.
error: script "test" exited with code 1
```
All the tests fail when I do `npm run test:node`

**Comment by webpro** [comment]
:rocket: _This pull request is included in v5.32.0. See [Release 5.32.0](https://github.com/webpro-nl/knip/releases/tag/5.32.0) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._

**Pull request merged**
