### PR TITLE
feat: coreutils to IGNORED_GLOBAL_BINARIES

### LINKED ISSUE #731: Add all coreutils to `IGNORED_GLOBAL_BINARIES`
Is there a reason not to? With the "last publish is at least 6 years ago" rule respected, of course. Full list available on Wikipedia [here](https://en.wikipedia.org/wiki/List_of_GNU_Core_Utilities_commands). Requesting because I'm looking for `sort`, `tr` and `uniq`.

### PR DESCRIPTION
**Pull request by chappelo**
closes #731

went through https://en.wikipedia.org/wiki/List_of_GNU_Core_Utilities_commands and added packages to IGNORED_GLOBAL_BINARIES which passed the following criteria below:

- exists on: https://www.npmjs.com/package/

- last published date at least 6 years ago

- not deprecated

### CODE REVIEW

**Comment by webpro** [comment]
Wow, nice @chappelo! Thanks, appreciated.

**Comment by webpro** [comment]
:rocket: _This pull request is included in v5.29.0. See [Release 5.29.0](https://github.com/webpro-nl/knip/releases/tag/5.29.0) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._

**Comment by alecmev** [comment]
Nice, thanks!

**Comment by chappelo** [comment]
> Wow, nice @chappelo! Thanks, appreciated.

you're most welcome!
would appreciate it if you could let me know, why **6** years?

**Comment by webpro** [comment]
Guess at the time (~2 years ago) it was just a strategic number to separate what I wanted in and not 😃 nothing formal here!

**Pull request merged**
